# Generated by Django 3.2.7 on 2021-09-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibaepo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checker',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lift',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='liftcheck',
            options={'managed': False},
        ),
    ]
